//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Curriculum
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Curriculum()
        {
            this.StudentsReports = new HashSet<StudentsReport>();
        }
    
        public int Id { get; set; }
        public Nullable<int> LessonId { get; set; }
        public Nullable<int> TeacherId { get; set; }
        public Nullable<int> TermId { get; set; }
    
        public virtual Lesson Lesson { get; set; }
        public virtual Teacher Teacher { get; set; }
        public virtual Term Term { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StudentsReport> StudentsReports { get; set; }
    }
}
